[phases.setup]
packages = ["python3", "gcc", "g++", "gnumake"]

[phases.build]
cmds = ["npm ci"]

[start]
cmd = "mkdir -p /app/persist/data /app/persist/data/properties /app/persist/uploads && node app.js"
